### ISSUE TITLE
Chrome extension broken due to manifest V3 (was Chrome failed by CORS)

### ISSUE THREAD

**Issue by Endle** [Endle/fireSeqSearch#19]
```
Access to fetch at 'http://127.0.0.1:3030/server_info' from origin 'https://www.google.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
127.0.0.1:3030/server_info:1          Failed to load resource: net::ERR_FAILED
main.js:148                  Uncaught (in promise) TypeError: Failed to fetch
    at main.js:148:12
    at main.js:157:3
```

**Comment by Endle** [comment]
I found this issue is harder than I expected 
https://www.chromium.org/Home/chromium-security/extension-content-script-fetches/
https://developer.chrome.com/docs/extensions/mv3/xhr/


Sorry for Chrome users - you need to wait for a bit longer.

PRs or suggestions are welcomed. As you see, my frontend knowledge is very limited.

**Comment by Endle** [comment]
I apologize to Chrome users.


First, Chrome is enforcing manifest V3 to new extensions. I have been working on migrating it to V3, but I have no progress yet. Therefore, fireSeqSearch is broken on Chrome yet.


Second, I didn't unpublish the Chrome extension in time.


My reply at reddit: https://www.reddit.com/r/logseq/comments/xdzyo3/comment/itsi4fl/?utm_source=share&utm_medium=web2x&context=3

**Comment by Endle** [comment]
Found a link but still no progress https://stackoverflow.com/questions/68772770/cors-chrome-extension-with-manifest-version-3

**Comment by Endle** [comment]
Bad news: After working for months, I haven't learnt how to write a Chrome extension.

Good news: I built a Tampermonkey version 

In short, if you're using Chrome, you can give [#fireSeqSearch](https://fediscience.org/tags/fireSeqSearch) a try!

[#logseq](https://fediscience.org/tags/logseq)


https://fediscience.org/@zhenboli/109306123317943374
